# Form implementation generated from reading ui file 'templates/dlgAbout.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(599, 470)
        Dialog.setModal(True)
        self.dlgAbout = QtWidgets.QTextEdit(parent=Dialog)
        self.dlgAbout.setEnabled(True)
        self.dlgAbout.setGeometry(QtCore.QRect(20, 190, 551, 231))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.dlgAbout.setFont(font)
        self.dlgAbout.setStyleSheet("background-color: rgba(240, 240, 240, 240);")
        self.dlgAbout.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.dlgAbout.setReadOnly(True)
        self.dlgAbout.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByKeyboard|QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextBrowserInteraction|QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.dlgAbout.setObjectName("dlgAbout")
        self.btnAceptar = QtWidgets.QPushButton(parent=Dialog)
        self.btnAceptar.setGeometry(QtCore.QRect(510, 430, 75, 23))
        self.btnAceptar.setObjectName("btnAceptar")
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(20, 170, 551, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(90, 50, 81, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("templates\\../img/icono.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(190, 10, 331, 161))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("templates\\../img/nombre-02.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 390, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByKeyboard|QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.dlgAbout.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; \"><span style=\" font-weight:600; color:#2c3e50;\">InmoTeis</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; \"><span style=\" color:#34495e;\">Versión 1.0.0</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; \"><span style=\" color:#34495e;\">Copyright © [1998-2024] Inmoteis&amp;Co. Todos los derechos reservados.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; \"><span style=\" color:#34495e;\">Este sitio web y su contenido están protegidos por derechos de autor y otras leyes de propiedad intelectual aplicables.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; \"><span style=\" color:#34495e;\">El uso de este producto está sujeto a los términos y condiciones.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; \"><span style=\" color:#34495e;\">Licenciado a: Luis Guillermo André Garrido</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; \"><span style=\" color:#34495e;\">El uso no autorizado de este sitio web, su contenido o materiales asociados puede dar lugar a acciones legales.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; \"><a href=\"https://github.com/TheLexa69/ProyectoDI\"><span style=\" text-decoration: underline; color:#3498db;\">Visita nuestro GitHub para más información.</span></a></p>\n"
"</body></html>"))
        self.btnAceptar.setText(_translate("Dialog", "Aceptar"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><a href=\"https://github.com/TheLexa69/ProyectoDI\"><span\n"
"           style=\" text-decoration: underline; color:#0000ff;\">*Enlace al GitHub.</span></a></p></body></html>\n"
"       "))
